#! /bin/sh -x

set -e

for var in USERNAME UID; do
    eval 'test -z "$'$var'"' && exit 1
done

useradd $USERNAME -u $UID -d $WORKDIR

dirs="$WORKDIR $PGDATA /data /var/log/copr-frontend"
for dir in $dirs
do
    test ! -d "$dir" && mkdir "$dir"
    chown "$USERNAME:$USERNAME" "$dir"
done

cat <<EOF > /init-shell
export PGDATA=$PGDATA
export PGPORT=$PGPORT
export PORT=$PORT
export USERNAME=$USERNAME
export CODE=$CODE
export FE_HOST=$FE_HOST
EOF
